version: '3'
services:

  fragment-a:
    command: bash -c 'yarn install && yarn start'
    environment:
      - NODE_ENV=development
    volumes:
      - ./fragment:/src
      - ./fragment/.remote/a:/src/.remote

  fragment-b:
    command: bash -c 'yarn install && yarn start'
    environment:
      - NODE_ENV=development
    volumes:
      - ./fragment:/src
      - ./fragment/.remote/b:/src/.remote

  shell:
    command: bash -c 'yarn install && yarn start'
    environment:
      - NODE_ENV=development
    volumes:
      - ./shell:/src
