root: true
parser: babel-eslint
extends:
  - airbnb-base
  - airbnb-base/rules/strict
  - prettier
overrides:
  - files: ['**/*.ts']
    parser: typescript-eslint-parser
    rules:
      no-dupe-class-members: off
      no-undef: off
      no-unused-vars: off
  - files: ['**/test/**/*.test.js']
    env:
      jest: true
rules:
  no-underscore-dangle: [error, { allowAfterThis: true }]
  no-restricted-syntax: [error, { selector: LabeledStatement }, { selector: WithStatement }]
settings:
  import/resolver:
    node:
      extensions: [.js, .ts, .json]
