root: true
parser: babel-eslint
extends:
  - airbnb-base
  - airbnb-base/rules/strict
  - prettier
rules:
  no-underscore-dangle: [error, { allowAfterThis: true }]
  no-restricted-syntax:
    [
      error,
      { selector: ForInStatement },
      { selector: LabeledStatement },
      { selector: WithStatement },
    ]
overrides:
  - files: ['**/*.ts']
    parser: typescript-eslint-parser
    rules:
      lines-between-class-members: off
      no-dupe-class-members: off
      no-undef: off
      no-unused-vars: off
      no-use-before-define: off
  - files: ['**/test/**/*.test.js']
    env:
      jest: true
  - files: ['**/{dev,test}/**']
    rules:
      import/no-extraneous-dependencies: [error, { devDependencies: true, packageDir: ['./'] }]
settings:
  import/resolver:
    node:
      extensions: [.js, .ts, .d.ts, .json]
